use crate::auth::cookie_manager::CookieManager;
use crate::entity::platform_session;
use sea_orm::EntityTrait;
use std::sync::Arc;
use tauri::{Emitter, Manager, State, Window};
#[cfg(target_os = "windows")]
use webview2_com::Microsoft::Web::WebView2::Win32::{
    ICoreWebView2GetCookiesCompletedHandler, ICoreWebView2GetCookiesCompletedHandler_Impl,
};
#[cfg(target_os = "windows")]
use windows::core::{Interface, HSTRING};

#[cfg(target_os = "windows")]
#[windows_implement::implement(ICoreWebView2GetCookiesCompletedHandler)]
pub struct CookieHandler {
    pub tx: std::sync::Mutex<Option<tokio::sync::oneshot::Sender<Result<String, String>>>>,
}

#[cfg(target_os = "windows")]
impl ICoreWebView2GetCookiesCompletedHandler_Impl for CookieHandler_Impl {
    #[allow(non_snake_case)]
    fn Invoke(
        &self,
        result: windows::core::HRESULT,
        cookie_list: windows::core::Ref<
            '_,
            webview2_com::Microsoft::Web::WebView2::Win32::ICoreWebView2CookieList,
        >,
    ) -> windows::core::Result<()> {
        let mut tx_lock = self.tx.lock().unwrap();
        if let Some(tx) = tx_lock.take() {
            result.ok()?;

            let cookie_list = match cookie_list.ok() {
                Ok(l) => l,
                Err(_) => {
                    let err: Result<String, String> = Err("No cookie list returned".into());
                    let _ = tx.send(err);
                    return Ok(());
                }
            };

            let mut count = 0;
            unsafe { cookie_list.Count(&mut count) }?;

            let mut netscape_cookies = String::new();
            netscape_cookies.push_str("# Netscape HTTP Cookie File\n");
            netscape_cookies.push_str("# This file is generated by VideoDownloaderPro\n\n");

            for i in 0..count {
                let cookie = unsafe { cookie_list.GetValueAtIndex(i) }?;

                let mut domain = windows::core::PWSTR::null();
                unsafe { cookie.Domain(&mut domain) }?;

                let mut path = windows::core::PWSTR::null();
                unsafe { cookie.Path(&mut path) }?;

                let mut secure = Default::default();
                unsafe { cookie.IsSecure(&mut secure) }?;

                let mut expires = 0.0;
                unsafe { cookie.Expires(&mut expires) }?;

                let mut name = windows::core::PWSTR::null();
                unsafe { cookie.Name(&mut name) }?;

                let mut value = windows::core::PWSTR::null();
                unsafe { cookie.Value(&mut value) }?;

                let domain_str = unsafe { domain.to_string().unwrap_or_default() };
                let path_str = unsafe { path.to_string().unwrap_or_default() };
                let name_str = unsafe { name.to_string().unwrap_or_default() };
                let value_str = unsafe { value.to_string().unwrap_or_default() };

                unsafe {
                    windows::Win32::System::Com::CoTaskMemFree(Some(domain.as_ptr() as *const _));
                    windows::Win32::System::Com::CoTaskMemFree(Some(path.as_ptr() as *const _));
                    windows::Win32::System::Com::CoTaskMemFree(Some(name.as_ptr() as *const _));
                    windows::Win32::System::Com::CoTaskMemFree(Some(value.as_ptr() as *const _));
                }

                let flag = if domain_str.starts_with('.') {
                    "TRUE"
                } else {
                    "FALSE"
                };
                let secure_bool: bool = secure.into();
                let secure_str = if secure_bool { "TRUE" } else { "FALSE" };

                netscape_cookies.push_str(&format!(
                    "{}\t{}\t{}\t{}\t{}\t{}\t{}\n",
                    domain_str, flag, path_str, secure_str, expires as i64, name_str, value_str
                ));
            }
            let _ = tx.send(Ok(netscape_cookies));
        }
        Ok(())
    }
}

use crate::AppState;

#[tauri::command]
pub async fn get_auth_status(
    state: State<'_, AppState>,
) -> Result<Vec<platform_session::Model>, String> {
    platform_session::Entity::find()
        .all(&state.db)
        .await
        .map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn update_session(
    window: Window,
    cookie_manager: State<'_, Arc<CookieManager>>,
    platform_id: String,
    cookies_str: String,
    method: String,
) -> Result<(), String> {
    cookie_manager
        .set_session(platform_id.clone(), cookies_str, method)
        .await
        .map_err(|e| e.to_string())?;

    // Emit event to update UI
    window
        .emit("session-status-changed", &platform_id)
        .map_err(|e| e.to_string())?;

    Ok(())
}

#[tauri::command]
pub async fn delete_session(
    window: Window,
    cookie_manager: State<'_, Arc<CookieManager>>,
    platform_id: String,
) -> Result<(), String> {
    cookie_manager
        .delete_session(&platform_id)
        .await
        .map_err(|e| e.to_string())?;

    // Emit event to update UI
    window
        .emit("session-status-changed", &platform_id)
        .map_err(|e| e.to_string())?;

    Ok(())
}

#[tauri::command]
pub async fn import_from_browser(
    platform_id: String,
    browser: String,
    window: Window,
    app_handle: tauri::AppHandle,
    cookie_manager: State<'_, Arc<CookieManager>>,
) -> Result<(), String> {
    let url = match platform_id.as_str() {
        "youtube" => "https://www.youtube.com",
        "tiktok" => "https://www.tiktok.com",
        "instagram" => "https://www.instagram.com",
        "x" => "https://x.com",
        _ => return Err("Unsupported platform".into()),
    };

    let cookies_content = if browser == "webview" {
        #[cfg(target_os = "windows")]
        {
            let existing_auth_label = format!("auth_{}", platform_id);
            let mut close_after_extraction = false;
            // Track the actual label of the window we use for extraction
            let actual_window_label: String;

            let auth_window = if let Some(w) = app_handle.get_webview_window(&existing_auth_label) {
                tracing::info!(
                    "Found existing auth window {}, using it for extraction",
                    existing_auth_label
                );
                actual_window_label = existing_auth_label;
                w
            } else {
                let unique_label = format!("auth_extract_{}_{}", platform_id, uuid::Uuid::new_v4());
                tracing::info!(
                    "Auth window not found, creating hidden window {} for extraction",
                    unique_label
                );
                close_after_extraction = true;
                actual_window_label = unique_label.clone();

                let app_local_data = app_handle
                    .path()
                    .app_local_data_dir()
                    .map_err(|e| e.to_string())?;
                let auth_data_dir = app_local_data.join("EBWebView_Auth");

                let w = tauri::WebviewWindowBuilder::new(
                    &app_handle,
                    &unique_label,
                    tauri::WebviewUrl::External(url.parse().unwrap()),
                )
                .title(format!("Login to {}", platform_id))
                .data_directory(auth_data_dir)
                .visible(false) // Hidden
                .build()
                .map_err(|e| e.to_string())?;

                // Wait for navigation/ready
                // We'll give it a moment to initialize the webview context
                tokio::time::sleep(std::time::Duration::from_millis(1000)).await;
                w
            };

            let (tx, rx) = tokio::sync::oneshot::channel();
            let tx_mutex = std::sync::Mutex::new(Some(tx));

            // We need to move data into the closure.
            // URL must be HSTRING.
            let uri = HSTRING::from(url);

            // use the window to access webview
            auth_window.with_webview(move |webview| {
                unsafe {
                    let webview_obj = webview.controller().CoreWebView2().unwrap();
                    let raw_ptr = windows::core::Interface::as_raw(&webview_obj);

                    // Cast to webview2-com ICoreWebView2_2 directly from raw pointer
                    // We assume ABI compatibility
                    // Use transmute_copy to handle bridging differing ICoreWebView2 types
                    let webview2: webview2_com::Microsoft::Web::WebView2::Win32::ICoreWebView2_2 = {
                        // WARN: Use ManuallyDrop so we don't accidentally call Release() on the COM object
                        // when the `unknown` wrapper falls out of scope, which causes 0xc000041d!
                        let unknown: std::mem::ManuallyDrop<webview2_com::Microsoft::Web::WebView2::Win32::ICoreWebView2> =
                            std::mem::transmute_copy(&raw_ptr);
                        unknown.cast().unwrap()
                    };
                    
                    let cookie_manager_webview = webview2.CookieManager().unwrap();
                    
                    let handler = CookieHandler { tx: tx_mutex };
                    // Coerce to the expected handler interface
                    let handler_interface: webview2_com::Microsoft::Web::WebView2::Win32::ICoreWebView2GetCookiesCompletedHandler = handler.into();
                    
                    cookie_manager_webview.GetCookies(&uri, &handler_interface).unwrap();
                }
            }).map_err(|e| format!("Failed to access webview: {}", e))?;

            // Wait for result
            let result = rx
                .await
                .map_err(|e| format!("Cookie extraction channel error: {}", e))??;

            // Navigate to about:blank to stop any media playback immediately
            tracing::info!(
                "Navigating window {} to about:blank to stop media...",
                actual_window_label
            );
            let _ = auth_window.eval("window.location.href = 'about:blank';");

            if close_after_extraction {
                // This was a temporary hidden window — destroy it after a short delay
                tracing::info!(
                    "Scheduling destruction of temporary extraction window: {}",
                    actual_window_label
                );
                let app_handle_clone = app_handle.clone();
                let label_for_close = actual_window_label.clone();
                tauri::async_runtime::spawn(async move {
                    tokio::time::sleep(std::time::Duration::from_millis(1500)).await;
                    let app_handle_inner = app_handle_clone.clone();
                    let _ = app_handle_clone.run_on_main_thread(move || {
                        if let Some(w) = app_handle_inner.get_webview_window(&label_for_close) {
                            tracing::info!(
                                "Destroying temporary extraction window: {}",
                                label_for_close
                            );
                            let _ = w.destroy();
                        }
                    });
                });
            } else {
                // This was the user's login window — close it now that extraction is done
                tracing::info!(
                    "Closing user login window after extraction: {}",
                    actual_window_label
                );
                let app_handle_clone = app_handle.clone();
                let label_for_close = actual_window_label.clone();
                tauri::async_runtime::spawn(async move {
                    tokio::time::sleep(std::time::Duration::from_millis(500)).await;
                    let app_handle_inner = app_handle_clone.clone();
                    let _ = app_handle_clone.run_on_main_thread(move || {
                        if let Some(w) = app_handle_inner.get_webview_window(&label_for_close) {
                            tracing::info!("Destroying user login window: {}", label_for_close);
                            let _ = w.destroy();
                        }
                    });
                });
            }

            result
        }
        #[cfg(not(target_os = "windows"))]
        {
            return Err("WebView cookie extraction only supported on Windows".into());
        }
    } else {
        // External browser logic (yt-dlp)
        let ytdlp_path = crate::sidecar::get_binary_path(
            &app_handle,
            crate::sidecar::types::SidecarBinary::YtDlp,
        )
        .map_err(|e| e.to_string())?;

        let temp_cookie_path = std::env::temp_dir().join(format!(
            "cookies_{}_{}.txt",
            platform_id,
            uuid::Uuid::new_v4()
        ));

        tracing::info!("Executing yt-dlp import from browser: {}", browser);

        let output = tokio::process::Command::new(ytdlp_path)
            .arg("--cookies-from-browser")
            .arg(&browser)
            .arg("--cookies")
            .arg(&temp_cookie_path)
            .arg("--skip-download")
            .arg("--verbose")
            .arg(url)
            .output()
            .await
            .map_err(|e| format!("Failed to execute yt-dlp: {}", e))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            if temp_cookie_path.exists() {
                let _ = tokio::fs::remove_file(&temp_cookie_path).await;
            }
            // Sanitize error message
            if stderr.contains("Failed to decrypt with DPAPI")
                || stderr.contains("App-Bound Encryption")
            {
                return Err("Browser security (App-Bound Encryption) blocked access. Please try the 'WebView' or 'Manual' tab.".into());
            } else if stderr.contains("cookie file is missing") || stderr.contains("Could not find")
            {
                return Err(
                    "Could not find cookies for this browser. Ensure you are logged in.".into(),
                );
            } else if stderr.contains("could not find") || stderr.contains("cookies database in") {
                return Err("Browser is not found. Please install it and try again.".into());
            }

            // Fallback generic message
            return Err("Browser import failed due to an unknown error. Please try the 'WebView' or 'Manual' tab.".into());
        }

        if !temp_cookie_path.exists() {
            return Err("yt-dlp did not create a cookie file.".into());
        }

        let content = tokio::fs::read_to_string(&temp_cookie_path)
            .await
            .map_err(|e| format!("Failed to read temp cookie file: {}", e))?;

        let _ = tokio::fs::remove_file(&temp_cookie_path).await;

        if content.trim().is_empty() {
            return Err("Imported cookie file was empty.".into());
        }
        content
    };

    cookie_manager
        .set_session(
            platform_id.clone(),
            cookies_content,
            format!("browser_import:{}", browser),
        )
        .await
        .map_err(|e| e.to_string())?;

    window
        .emit("session-status-changed", &platform_id)
        .map_err(|e| e.to_string())?;

    Ok(())
}

#[tauri::command]
pub async fn open_login_window(
    app_handle: tauri::AppHandle,
    platform_id: String,
) -> Result<(), String> {
    let url = match platform_id.as_str() {
        "youtube" => "https://accounts.google.com/ServiceLogin?service=youtube",
        "tiktok" => "https://www.tiktok.com/login",
        "instagram" => "https://www.instagram.com/accounts/login/",
        "x" => "https://x.com/i/flow/login",
        _ => return Err("Unsupported platform".into()),
    };

    let label = format!("auth_{}", platform_id);

    if let Some(w) = app_handle.get_webview_window(&label) {
        let _ = w.set_focus();
        return Ok(());
    }

    let app_local_data = app_handle
        .path()
        .app_local_data_dir()
        .map_err(|e| e.to_string())?;
    let auth_data_dir = app_local_data.join("EBWebView_Auth");

    // Use a realistic Chrome User-Agent to avoid bot detection (especially TikTok)
    let chrome_ua = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

    let webview_window = tauri::WebviewWindowBuilder::new(
        &app_handle,
        &label,
        tauri::WebviewUrl::External(url.parse().unwrap()),
    )
    .title(format!("Login to {}", platform_id))
    .data_directory(auth_data_dir)
    .user_agent(chrome_ua)
    .inner_size(1280.0, 800.0)
    .build()
    .map_err(|e| e.to_string())?;

    // Disable WebView2 automation flags that sites use for bot detection
    #[cfg(target_os = "windows")]
    {
        let _ = webview_window.with_webview(|webview| {
            unsafe {
                use webview2_com::Microsoft::Web::WebView2::Win32::ICoreWebView2Settings;
                use windows::core::Interface;

                let webview_obj = webview.controller().CoreWebView2().unwrap();
                let raw_ptr = Interface::as_raw(&webview_obj);
                let settings: std::mem::ManuallyDrop<ICoreWebView2Settings> =
                    std::mem::transmute_copy(&raw_ptr);
                if let Ok(settings8) = settings.cast::<webview2_com::Microsoft::Web::WebView2::Win32::ICoreWebView2Settings8>() {
                    // Disable "is browser automated" flag — reduces bot detection
                    let _ = settings8.SetIsGeneralAutofillEnabled(true.into());
                }
            }
        });
    }

    Ok(())
}

#[tauri::command]
pub async fn verify_session_status(
    window: Window,
    state: State<'_, AppState>,
    cookie_manager: State<'_, Arc<CookieManager>>,
    platform_id: String,
) -> Result<bool, String> {
    let cookies_str = cookie_manager
        .get_netscape_cookies(&platform_id)
        .await
        .map_err(|e| e.to_string())?;

    if let Some(cookies) = cookies_str {
        let is_valid =
            crate::auth::api::UsernameFetcher::check_session_validity(&platform_id, &cookies)
                .await
                .unwrap_or(false);

        use crate::entity::platform_session;
        use chrono::Utc;
        use sea_orm::{ActiveModelTrait, EntityTrait, Set};

        if let Ok(Some(session)) = platform_session::Entity::find_by_id(&platform_id)
            .one(&state.db)
            .await
        {
            let mut active_session: platform_session::ActiveModel = session.into();
            active_session.status = Set(if is_valid {
                "ACTIVE".to_string()
            } else {
                "EXPIRED".to_string()
            });
            active_session.last_verified = Set(Some(Utc::now()));
            if !is_valid {
                active_session.error_message =
                    Set(Some("Session expired. Please reconnect.".to_string()));
            } else {
                active_session.error_message = Set(None);
            }
            active_session.updated_at = Set(Utc::now());

            let _ = active_session.update(&state.db).await;
        }

        let _ = window.emit("session-status-changed", &platform_id);
        Ok(is_valid)
    } else {
        Err("Session not found".into())
    }
}

#[tauri::command]
pub async fn verify_all_sessions(
    window: Window,
    state: State<'_, AppState>,
    cookie_manager: State<'_, Arc<CookieManager>>,
) -> Result<(), String> {
    use crate::entity::platform_session;
    use sea_orm::EntityTrait;

    let sessions = platform_session::Entity::find()
        .all(&state.db)
        .await
        .map_err(|e| e.to_string())?;

    // We spawn a detached task so we don't block the UI while it sequentially checks
    let window_clone = window.clone();
    let db_clone = state.db.clone();
    let cm_clone = (*cookie_manager).clone();

    tauri::async_runtime::spawn(async move {
        for session in sessions {
            if session.status != "ACTIVE" && session.status != "EXPIRED" {
                continue;
            }
            if let Ok(Some(cookies)) = cm_clone.get_netscape_cookies(&session.platform_id).await {
                let is_valid = crate::auth::api::UsernameFetcher::check_session_validity(
                    &session.platform_id,
                    &cookies,
                )
                .await
                .unwrap_or(false);

                use chrono::Utc;
                use sea_orm::{ActiveModelTrait, Set};

                let mut active_session: platform_session::ActiveModel = session.clone().into();
                active_session.status = Set(if is_valid {
                    "ACTIVE".to_string()
                } else {
                    "EXPIRED".to_string()
                });
                active_session.last_verified = Set(Some(Utc::now()));
                if !is_valid {
                    active_session.error_message =
                        Set(Some("Session expired. Please reconnect.".to_string()));
                } else {
                    active_session.error_message = Set(None);
                }
                active_session.updated_at = Set(Utc::now());

                let _ = active_session.update(&db_clone).await;

                let _ = window_clone.emit("session-status-changed", &session.platform_id);
            }

            // Sleep to avoid rate limits
            tokio::time::sleep(tokio::time::Duration::from_secs(2)).await;
        }
    });

    Ok(())
}
