/**
 * Shared types for Format & Quality Selection (Phase 5.6).
 * These mirror the Rust backend structs from `metadata::format_processor`.
 */

// ─── ProcessedMetadata (returned by fetch_metadata_command) ─────────────────

export interface ProcessedMetadata {
    id: string;
    title: string;
    uploader: string | null;
    duration: number | null;
    thumbnail_url: string | null;
    video_qualities: VideoQuality[];
    audio_tracks: AudioTrack[];
    subtitle_tracks: SubtitleTrack[];
}

export interface VideoQuality {
    /** Human-readable label, e.g. "1080p • 60fps • HDR • MP4" */
    label: string;
    /** yt-dlp format_id for the -f flag */
    format_id: string;
    height: number;
    fps: number | null;
    /** User-friendly codec: "H.264", "VP9", "AV1" */
    vcodec: string;
    /** "SDR", "HDR", "HDR10" */
    dynamic_range: string;
    /** "MP4", "WebM", "MKV" */
    container: string;
    filesize: number | null;
    /** True if this stream is muxed (has both video + audio) */
    has_audio: boolean;
}

export interface AudioTrack {
    /** Human-readable label, e.g. "English • AAC 128kbps" */
    label: string;
    /** yt-dlp format_id */
    format_id: string;
    /** "AAC", "Opus", "MP3" */
    acodec: string;
    bitrate_kbps: number | null;
    sample_rate: number | null;
    channels: number | null;
    language: string | null;
    filesize: number | null;
    /** True if this is the recommended default track */
    is_default: boolean;
}

export interface SubtitleTrack {
    /** ISO 639-1 language code: "en", "es", "ja" */
    language_code: string;
    /** Human-readable: "English", "Spanish" */
    label: string;
    /** True if auto-generated by the platform */
    is_auto_generated: boolean;
}

// ─── DownloadOptions (sent to create_download_task) ─────────────────────────

export interface DownloadOptions {
    /** Specific video format_id. undefined = best */
    format_id?: string;
    /** Specific audio format_id. undefined = bestaudio */
    audio_format_id?: string;
    /** Extract audio only (no video) */
    audio_only: boolean;
    /** Output audio format when extracting: "mp3", "opus", "m4a" */
    audio_extract_format?: string;
    /** Subtitle languages to download: ["en", "es"] */
    subtitle_langs: string[];
    /** Embed subtitles into the video container */
    embed_subs: boolean;
    /** Override output container: "mp4", "mkv", "webm" */
    container?: string;
}

// ─── Helpers ────────────────────────────────────────────────────────────────

/** Format bytes into a human-readable string */
export function formatFileSize(bytes: number | null): string {
    if (bytes == null || bytes <= 0) return '';
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    if (bytes < 1024 * 1024 * 1024) return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
    return `${(bytes / (1024 * 1024 * 1024)).toFixed(2)} GB`;
}
