//! Transforms raw yt-dlp format data into clean, UI-friendly types for the frontend.
//!
//! The main entry point is [`process_metadata`], which takes a [`YtDlpVideo`] and returns
//! a [`ProcessedMetadata`] containing deduplicated video qualities, audio tracks, and
//! subtitle tracks ready for display in the `AddDownloadModal`.

use serde::{Deserialize, Serialize};
use std::collections::HashSet;

use super::models::YtDlpVideo;

// ─── Output Types (sent to Frontend) ───────────────────────────────────────────

/// Clean, UI-ready metadata returned by the `fetch_metadata_command` IPC.
#[derive(Debug, Clone, Serialize)]
pub struct ProcessedMetadata {
    pub id: String,
    pub title: String,
    pub uploader: Option<String>,
    pub duration: Option<f64>,
    pub thumbnail_url: Option<String>,
    pub video_qualities: Vec<VideoQuality>,
    pub audio_tracks: Vec<AudioTrack>,
    pub subtitle_tracks: Vec<SubtitleTrack>,
}

/// A deduplicated video quality option.
#[derive(Debug, Clone, Serialize)]
pub struct VideoQuality {
    /// Human-readable label, e.g. "1080p 60fps HDR"
    pub label: String,
    /// yt-dlp format_id for the `-f` flag
    pub format_id: String,
    pub height: u32,
    pub fps: Option<f64>,
    /// User-friendly codec name: "H.264", "VP9", "AV1"
    pub vcodec: String,
    /// "SDR", "HDR", "HDR10"
    pub dynamic_range: String,
    /// "MP4", "WebM", "MKV"
    pub container: String,
    pub filesize: Option<u64>,
    /// True if this is a muxed stream (has both video + audio)
    pub has_audio: bool,
}

/// An audio-only track option.
#[derive(Debug, Clone, Serialize)]
pub struct AudioTrack {
    /// Human-readable label, e.g. "English • AAC 128kbps"
    pub label: String,
    /// yt-dlp format_id for the `-f` flag
    pub format_id: String,
    /// User-friendly codec name: "AAC", "Opus", "MP3"
    pub acodec: String,
    pub bitrate_kbps: Option<f64>,
    pub sample_rate: Option<u32>,
    pub channels: Option<u32>,
    pub language: Option<String>,
    pub filesize: Option<u64>,
    /// True if this is the highest bitrate track (recommended default)
    pub is_default: bool,
}

/// A subtitle track option.
#[derive(Debug, Clone, Serialize)]
pub struct SubtitleTrack {
    /// ISO 639-1 language code, e.g. "en", "es", "ja"
    pub language_code: String,
    /// Human-readable name, e.g. "English", "Spanish"
    pub label: String,
    /// True if from `automatic_captions` (auto-generated by the platform)
    pub is_auto_generated: bool,
}

/// Structured download options built by the frontend and sent to the backend.
/// Serialized JSON is stored in `download_tasks.format_selection`.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct DownloadOptions {
    /// Specific video format_id to download. None = best.
    #[serde(default)]
    pub format_id: Option<String>,
    /// Specific audio format_id. None = bestaudio.
    #[serde(default)]
    pub audio_format_id: Option<String>,
    /// If true, extract audio only (no video).
    #[serde(default)]
    pub audio_only: bool,
    /// Output format when extracting audio: "mp3", "opus", "m4a", "aac".
    #[serde(default)]
    pub audio_extract_format: Option<String>,
    /// Subtitle languages to download: ["en", "es"]. Empty = no subtitles.
    #[serde(default)]
    pub subtitle_langs: Vec<String>,
    /// Embed subtitles directly into the video container.
    #[serde(default)]
    pub embed_subs: bool,
    /// Override output container: "mp4", "mkv", "webm". None = auto.
    #[serde(default)]
    pub container: Option<String>,
}

// ─── Processing Logic ──────────────────────────────────────────────────────────

/// Transforms a raw [`YtDlpVideo`] into a [`ProcessedMetadata`] with
/// deduplicated, sorted, and human-readable format information.
pub fn process_metadata(video: &YtDlpVideo) -> ProcessedMetadata {
    let video_qualities = extract_video_qualities(video);
    let audio_tracks = extract_audio_tracks(video);
    let subtitle_tracks = extract_subtitle_tracks(video);

    ProcessedMetadata {
        id: video.id.clone(),
        title: video.title.clone(),
        uploader: video.uploader.clone().or_else(|| video.channel.clone()),
        duration: video.duration,
        thumbnail_url: video.best_thumbnail(),
        video_qualities,
        audio_tracks,
        subtitle_tracks,
    }
}

/// Extract, deduplicate, and sort video quality options.
fn extract_video_qualities(video: &YtDlpVideo) -> Vec<VideoQuality> {
    let formats = match &video.formats {
        Some(f) => f,
        None => return vec![],
    };

    // Filter to formats that have video (vcodec != "none")
    let video_formats: Vec<_> = formats
        .iter()
        .filter(|f| {
            let vc = f.vcodec.as_deref().unwrap_or("none");
            vc != "none" && f.height.unwrap_or(0) > 0
        })
        .collect();

    // Group by (height, rounded_fps, dynamic_range) — keep the best bitrate per group
    let mut seen = HashSet::new();
    let mut qualities: Vec<VideoQuality> = Vec::new();

    // Sort by height desc, fps desc, tbr desc to pick best first
    let mut sorted = video_formats;
    sorted.sort_by(|a, b| {
        let height_cmp = b.height.unwrap_or(0).cmp(&a.height.unwrap_or(0));
        let fps_cmp = b
            .fps
            .unwrap_or(0.0)
            .partial_cmp(&a.fps.unwrap_or(0.0))
            .unwrap_or(std::cmp::Ordering::Equal);
        let tbr_cmp = b
            .tbr
            .unwrap_or(0.0)
            .partial_cmp(&a.tbr.unwrap_or(0.0))
            .unwrap_or(std::cmp::Ordering::Equal);
        height_cmp.then(fps_cmp).then(tbr_cmp)
    });

    for f in &sorted {
        let height = f.height.unwrap_or(0);
        let fps = f.fps.unwrap_or(30.0);
        let dr = normalize_dynamic_range(f.dynamic_range.as_deref());
        let ext = f.ext.as_deref().unwrap_or("mp4");

        // Round fps for grouping: 30 or less = "30", 48-60 = "60"
        let fps_group = if fps > 48.0 { 60 } else { 30 };

        let key = format!("{height}_{fps_group}_{dr}_{ext}");
        if seen.contains(&key) {
            continue;
        }
        seen.insert(key);

        let has_audio = f.acodec.as_deref().unwrap_or("none") != "none";
        let fps_display = if fps > 48.0 { Some(fps) } else { None };
        let label = build_quality_label(height, fps_display, &dr, ext);

        qualities.push(VideoQuality {
            label,
            format_id: f.format_id.clone(),
            height,
            fps: if fps > 0.0 { Some(fps) } else { None },
            vcodec: codec_display_name(f.vcodec.as_deref().unwrap_or("unknown")),
            dynamic_range: dr,
            container: container_display_name(ext),
            filesize: f.filesize.or(f.filesize_approx),
            has_audio,
        });
    }

    qualities
}

/// Extract, deduplicate, and sort audio track options.
fn extract_audio_tracks(video: &YtDlpVideo) -> Vec<AudioTrack> {
    let formats = match &video.formats {
        Some(f) => f,
        None => return vec![],
    };

    // Filter to audio-only formats (acodec != "none" AND vcodec == "none")
    let mut audio_formats: Vec<_> = formats
        .iter()
        .filter(|f| {
            let ac = f.acodec.as_deref().unwrap_or("none");
            let vc = f.vcodec.as_deref().unwrap_or("none");
            ac != "none" && vc == "none"
        })
        .collect();

    // Sort by bitrate descending (highest quality first)
    audio_formats.sort_by(|a, b| {
        b.abr
            .unwrap_or(0.0)
            .partial_cmp(&a.abr.unwrap_or(0.0))
            .unwrap_or(std::cmp::Ordering::Equal)
    });

    // Deduplicate by (language, acodec)
    let mut seen = HashSet::new();
    let mut tracks: Vec<AudioTrack> = Vec::new();
    let mut is_first = true;

    for f in &audio_formats {
        let lang = f.language.clone().unwrap_or_default();
        let ac = f.acodec.as_deref().unwrap_or("unknown");
        let key = format!("{lang}_{ac}");

        if seen.contains(&key) {
            continue;
        }
        seen.insert(key);

        let codec_name = codec_display_name(ac);
        let bitrate = f.abr;
        let label = build_audio_label(f.language.as_deref(), &codec_name, bitrate);

        tracks.push(AudioTrack {
            label,
            format_id: f.format_id.clone(),
            acodec: codec_name,
            bitrate_kbps: bitrate,
            sample_rate: f.asr,
            channels: f.audio_channels,
            language: f.language.clone(),
            filesize: f.filesize.or(f.filesize_approx),
            is_default: is_first,
        });

        is_first = false;
    }

    tracks
}

/// Extract subtitle tracks from both manual and automatic captions.
fn extract_subtitle_tracks(video: &YtDlpVideo) -> Vec<SubtitleTrack> {
    let mut tracks: Vec<SubtitleTrack> = Vec::new();
    let mut seen_langs = HashSet::new();

    // Manual subtitles first (higher quality)
    if let Some(subs) = &video.subtitles {
        for (lang_code, entries) in subs {
            if seen_langs.contains(lang_code) {
                continue;
            }
            seen_langs.insert(lang_code.clone());

            let label = entries
                .first()
                .and_then(|e| e.name.clone())
                .unwrap_or_else(|| language_display_name(lang_code));

            tracks.push(SubtitleTrack {
                language_code: lang_code.clone(),
                label,
                is_auto_generated: false,
            });
        }
    }

    // Auto-generated captions (marked as such)
    if let Some(auto_caps) = &video.automatic_captions {
        for (lang_code, entries) in auto_caps {
            if seen_langs.contains(lang_code) {
                continue; // Manual sub already exists for this language
            }
            seen_langs.insert(lang_code.clone());

            let base_label = entries
                .first()
                .and_then(|e| e.name.clone())
                .unwrap_or_else(|| language_display_name(lang_code));

            tracks.push(SubtitleTrack {
                language_code: lang_code.clone(),
                label: base_label,
                is_auto_generated: true,
            });
        }
    }

    // Sort: non-auto first, then alphabetically by label
    tracks.sort_by(|a, b| {
        a.is_auto_generated
            .cmp(&b.is_auto_generated)
            .then_with(|| a.label.cmp(&b.label))
    });

    tracks
}

// ─── Helpers ───────────────────────────────────────────────────────────────────

/// Map yt-dlp codec strings to human-readable names.
fn codec_display_name(raw: &str) -> String {
    let lower = raw.to_lowercase();
    if lower.starts_with("avc1") || lower.starts_with("h264") || lower == "h.264" {
        "H.264".to_string()
    } else if lower.starts_with("vp09") || lower.starts_with("vp9") {
        "VP9".to_string()
    } else if lower.starts_with("av01") || lower.starts_with("av1") {
        "AV1".to_string()
    } else if lower.starts_with("hev1") || lower.starts_with("hvc1") || lower.starts_with("hevc") {
        "H.265".to_string()
    } else if lower.starts_with("mp4a") || lower == "aac" {
        "AAC".to_string()
    } else if lower == "opus" {
        "Opus".to_string()
    } else if lower == "mp3" || lower.starts_with("mp3") {
        "MP3".to_string()
    } else if lower == "vorbis" {
        "Vorbis".to_string()
    } else if lower == "flac" {
        "FLAC".to_string()
    } else {
        raw.to_uppercase()
    }
}

/// Map file extensions to display container names.
fn container_display_name(ext: &str) -> String {
    match ext.to_lowercase().as_str() {
        "mp4" | "m4a" | "m4v" => "MP4".to_string(),
        "webm" => "WebM".to_string(),
        "mkv" => "MKV".to_string(),
        "mov" => "MOV".to_string(),
        "avi" => "AVI".to_string(),
        "flv" => "FLV".to_string(),
        "ogg" | "ogv" => "OGG".to_string(),
        _ => ext.to_uppercase(),
    }
}

/// Normalize dynamic range values.
fn normalize_dynamic_range(raw: Option<&str>) -> String {
    match raw
        .unwrap_or("SDR")
        .to_uppercase()
        .trim()
        .replace(' ', "")
        .as_str()
    {
        "HDR" | "HDR10" | "HDR10+" => raw.unwrap_or("SDR").to_uppercase(),
        "HLG" => "HLG".to_string(),
        "DV" | "DOLBYVISION" => "Dolby Vision".to_string(),
        _ => "SDR".to_string(),
    }
}

/// Build a human-readable quality label like "1080p 60fps HDR".
fn build_quality_label(height: u32, fps: Option<f64>, dynamic_range: &str, ext: &str) -> String {
    let mut parts = vec![format!("{}p", height)];

    if let Some(f) = fps {
        parts.push(format!("{}fps", f.round() as u32));
    }

    if dynamic_range != "SDR" {
        parts.push(dynamic_range.to_string());
    }

    let container = container_display_name(ext);
    parts.push(container);

    parts.join(" • ")
}

/// Build a human-readable audio track label like "English • AAC 128kbps".
fn build_audio_label(language: Option<&str>, codec: &str, bitrate: Option<f64>) -> String {
    let mut parts = Vec::new();

    if let Some(lang) = language {
        if !lang.is_empty() {
            parts.push(language_display_name(lang));
        }
    }

    let mut codec_part = codec.to_string();
    if let Some(br) = bitrate {
        codec_part.push_str(&format!(" {}kbps", br.round() as u32));
    }
    parts.push(codec_part);

    parts.join(" • ")
}

/// Map ISO 639 language codes to display names.
fn language_display_name(code: &str) -> String {
    match code.to_lowercase().as_str() {
        "en" | "en-us" | "en-gb" => "English".to_string(),
        "es" | "es-es" | "es-419" => "Spanish".to_string(),
        "fr" | "fr-fr" => "French".to_string(),
        "de" | "de-de" => "German".to_string(),
        "pt" | "pt-br" => "Portuguese".to_string(),
        "it" | "it-it" => "Italian".to_string(),
        "ja" | "ja-jp" => "Japanese".to_string(),
        "ko" | "ko-kr" => "Korean".to_string(),
        "zh" | "zh-cn" | "zh-hans" => "Chinese (Simplified)".to_string(),
        "zh-tw" | "zh-hant" => "Chinese (Traditional)".to_string(),
        "ru" | "ru-ru" => "Russian".to_string(),
        "ar" | "ar-sa" => "Arabic".to_string(),
        "hi" | "hi-in" => "Hindi".to_string(),
        "nl" | "nl-nl" => "Dutch".to_string(),
        "sv" | "sv-se" => "Swedish".to_string(),
        "no" | "nb" | "nn" => "Norwegian".to_string(),
        "da" | "da-dk" => "Danish".to_string(),
        "fi" | "fi-fi" => "Finnish".to_string(),
        "pl" | "pl-pl" => "Polish".to_string(),
        "tr" | "tr-tr" => "Turkish".to_string(),
        "id" | "id-id" => "Indonesian".to_string(),
        "th" | "th-th" => "Thai".to_string(),
        "vi" | "vi-vn" => "Vietnamese".to_string(),
        "uk" | "uk-ua" => "Ukrainian".to_string(),
        "cs" | "cs-cz" => "Czech".to_string(),
        "el" | "el-gr" => "Greek".to_string(),
        "he" | "iw" => "Hebrew".to_string(),
        "ro" | "ro-ro" => "Romanian".to_string(),
        "hu" | "hu-hu" => "Hungarian".to_string(),
        "ca" | "ca-es" => "Catalan".to_string(),
        _ => code.to_uppercase(),
    }
}

// ─── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::metadata::models::{SubtitleMap, YtDlpFormat, YtDlpSubtitle, YtDlpVideo};

    /// Build a minimal YtDlpVideo for testing.
    fn make_test_video(
        formats: Vec<YtDlpFormat>,
        subtitles: Option<SubtitleMap>,
        auto_caps: Option<SubtitleMap>,
    ) -> YtDlpVideo {
        YtDlpVideo {
            id: "test123".to_string(),
            title: "Test Video".to_string(),
            description: None,
            uploader: Some("TestChannel".to_string()),
            uploader_id: None,
            uploader_url: None,
            channel: None,
            channel_id: None,
            channel_url: None,
            upload_date: None,
            duration: Some(120.0),
            view_count: None,
            like_count: None,
            webpage_url: None,
            original_url: None,
            thumbnails: None,
            formats: Some(formats),
            subtitles,
            automatic_captions: auto_caps,
            requested_subtitles: None,
            playlist_index: None,
            playlist_title: None,
            playlist_id: None,
        }
    }

    /// Build a video-only YtDlpFormat.
    fn video_format(id: &str, height: u32, fps: f64, vcodec: &str, ext: &str) -> YtDlpFormat {
        YtDlpFormat {
            format_id: id.to_string(),
            url: None,
            ext: Some(ext.to_string()),
            width: Some((height as f64 * 16.0 / 9.0) as u32),
            height: Some(height),
            tbr: Some(height as f64 * 5.0),
            vbr: Some(height as f64 * 4.0),
            abr: None,
            asr: None,
            fps: Some(fps),
            vcodec: Some(vcodec.to_string()),
            acodec: Some("none".to_string()),
            audio_channels: None,
            container: None,
            protocol: None,
            dynamic_range: Some("SDR".to_string()),
            resolution: Some(format!(
                "{}x{}",
                (height as f64 * 16.0 / 9.0) as u32,
                height
            )),
            format_note: Some(format!("{}p", height)),
            language: None,
            filesize: Some(height as u64 * 100_000),
            filesize_approx: None,
        }
    }

    /// Build an audio-only YtDlpFormat.
    fn audio_format(id: &str, acodec: &str, abr: f64, lang: Option<&str>) -> YtDlpFormat {
        YtDlpFormat {
            format_id: id.to_string(),
            url: None,
            ext: Some("m4a".to_string()),
            width: None,
            height: None,
            tbr: Some(abr),
            vbr: None,
            abr: Some(abr),
            asr: Some(44100),
            fps: None,
            vcodec: Some("none".to_string()),
            acodec: Some(acodec.to_string()),
            audio_channels: Some(2),
            container: None,
            protocol: None,
            dynamic_range: None,
            resolution: None,
            format_note: None,
            language: lang.map(|l| l.to_string()),
            filesize: Some(abr as u64 * 10_000),
            filesize_approx: None,
        }
    }

    #[test]
    fn test_video_quality_extraction_and_dedup() {
        let formats = vec![
            video_format("137", 1080, 30.0, "avc1.64001f", "mp4"),
            video_format("248", 1080, 30.0, "vp09.00.31", "webm"),
            video_format("136", 720, 30.0, "avc1.4d401f", "mp4"),
            video_format("298", 720, 60.0, "avc1.4d4020", "mp4"),
        ];
        let video = make_test_video(formats, None, None);
        let result = process_metadata(&video);

        assert_eq!(result.video_qualities.len(), 4);
        // First should be 1080p (highest)
        assert_eq!(result.video_qualities[0].height, 1080);
        // Should have correct codec display names
        assert_eq!(result.video_qualities[0].vcodec, "H.264");
        assert_eq!(result.video_qualities[1].vcodec, "VP9");
    }

    #[test]
    fn test_audio_track_extraction() {
        let formats = vec![
            audio_format("140", "mp4a.40.2", 128.0, Some("en")),
            audio_format("251", "opus", 160.0, Some("en")),
            audio_format("250", "opus", 64.0, Some("en")),
            audio_format("249", "opus", 48.0, Some("es")),
        ];
        let video = make_test_video(formats, None, None);
        let result = process_metadata(&video);

        // Should dedup by (language, codec), keeping highest bitrate
        // en+opus (160), en+mp4a (128), es+opus (48)
        assert_eq!(result.audio_tracks.len(), 3);
        // First (highest bitrate) should be default
        assert!(result.audio_tracks[0].is_default);
        assert_eq!(result.audio_tracks[0].acodec, "Opus");
    }

    #[test]
    fn test_subtitle_extraction() {
        let mut manual_subs = SubtitleMap::new();
        manual_subs.insert(
            "en".to_string(),
            vec![YtDlpSubtitle {
                ext: "vtt".to_string(),
                url: Some("https://example.com/en.vtt".to_string()),
                name: Some("English".to_string()),
            }],
        );

        let mut auto_caps = SubtitleMap::new();
        auto_caps.insert(
            "en".to_string(),
            vec![YtDlpSubtitle {
                ext: "vtt".to_string(),
                url: None,
                name: Some("English (auto)".to_string()),
            }],
        );
        auto_caps.insert(
            "es".to_string(),
            vec![YtDlpSubtitle {
                ext: "vtt".to_string(),
                url: None,
                name: Some("Spanish (auto)".to_string()),
            }],
        );

        let video = make_test_video(vec![], Some(manual_subs), Some(auto_caps));
        let result = process_metadata(&video);

        // "en" should be manual (not auto), "es" should be auto
        assert_eq!(result.subtitle_tracks.len(), 2);

        let en = result
            .subtitle_tracks
            .iter()
            .find(|t| t.language_code == "en")
            .unwrap();
        assert!(!en.is_auto_generated); // Manual takes priority
        assert_eq!(en.label, "English");

        let es = result
            .subtitle_tracks
            .iter()
            .find(|t| t.language_code == "es")
            .unwrap();
        assert!(es.is_auto_generated);
    }

    #[test]
    fn test_codec_display_names() {
        assert_eq!(codec_display_name("avc1.64001f"), "H.264");
        assert_eq!(codec_display_name("vp09.00.31.08"), "VP9");
        assert_eq!(codec_display_name("av01.0.08M"), "AV1");
        assert_eq!(codec_display_name("mp4a.40.2"), "AAC");
        assert_eq!(codec_display_name("opus"), "Opus");
        assert_eq!(codec_display_name("hev1.1.6.L120"), "H.265");
    }

    #[test]
    fn test_dynamic_range_normalization() {
        assert_eq!(normalize_dynamic_range(None), "SDR");
        assert_eq!(normalize_dynamic_range(Some("SDR")), "SDR");
        assert_eq!(normalize_dynamic_range(Some("HDR10")), "HDR10");
        assert_eq!(normalize_dynamic_range(Some("HDR")), "HDR");
    }

    #[test]
    fn test_quality_label_building() {
        assert_eq!(build_quality_label(1080, None, "SDR", "mp4"), "1080p • MP4");
        assert_eq!(
            build_quality_label(1080, Some(60.0), "SDR", "mp4"),
            "1080p • 60fps • MP4"
        );
        assert_eq!(
            build_quality_label(2160, Some(60.0), "HDR10", "webm"),
            "2160p • 60fps • HDR10 • WebM"
        );
    }

    #[test]
    fn test_empty_formats() {
        let video = make_test_video(vec![], None, None);
        let result = process_metadata(&video);
        assert!(result.video_qualities.is_empty());
        assert!(result.audio_tracks.is_empty());
        assert!(result.subtitle_tracks.is_empty());
    }
}
